from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence

from .answerer import AnswerConfig, _build_prompt, _call_gemini


@dataclass
class VerificationIssue:
    type: str  # e.g. "unsupported_claim", "missing_context", "other"
    description: str
    citation_labels: List[str]


@dataclass
class VerificationResult:
    is_grounded: bool
    is_complete: bool
    issues: List[VerificationIssue]


def _build_verifier_prompt(
    query: str, answer: str, chunks: Sequence[Dict[str, Any]]
) -> str:
    """
    Build a prompt asking Gemini to evaluate groundedness and completeness.
    The model must output STRICT JSON.
    """
    lines: List[str] = []
    lines.append(
        "You are a verification assistant for a Retrieval-Augmented Generation (RAG) QA system in astronomy."
    )
    lines.append(
        "You will be given a user QUESTION, an ANSWER generated by another model, and numbered CONTEXT CHUNKS."
    )
    lines.append("")
    lines.append("Your tasks:")
    lines.append("1. Check GROUNDEDNESS: Are the factual claims in the ANSWER supported by at least one context chunk?")
    lines.append(
        "2. Check COMPLETENESS: Does the ANSWER address the important parts of the QUESTION using the available context?"
    )
    lines.append("")
    lines.append("If you find issues:")
    lines.append(
        "- For UNSUPPORTED_CLAIMS: describe the claim and explain why no chunk clearly supports it."
    )
    lines.append(
        "- For MISSING_CONTEXT: describe what part of the question was not answered or was only partially answered."
    )
    lines.append("")
    lines.append("Output STRICT JSON with this exact shape:")
    lines.append(
        '{'
        '"is_grounded": <true_or_false>, '
        '"is_complete": <true_or_false>, '
        '"issues": ['
        '  {"type": "unsupported_claim", "description": "text", "citation_labels": ["[1]", "[2]"]},'
        '  {"type": "missing_context", "description": "text", "citation_labels": []}'
        ' ]'
        '}'
    )
    lines.append("Do not add any extra keys. Do not add explanations outside the JSON.")
    lines.append("")
    lines.append("CONTEXT CHUNKS:")
    for idx, c in enumerate(chunks, start=1):
        src = c.get("doc_source", "")
        meta = c.get("metadata", {}) or {}
        page = meta.get("page")
        header = f"[{idx}]"
        if src:
            header += f" source={src}"
        if page is not None:
            header += f" page={page}"
        lines.append(header)
        lines.append(c.get("text", ""))
        lines.append("")

    lines.append("QUESTION:")
    lines.append(query.strip())
    lines.append("")
    lines.append("ANSWER:")
    lines.append(answer.strip())
    lines.append("")
    lines.append("Now produce ONLY the JSON object as specified.")

    return "\n".join(lines)


def verify_answer(
    query: str,
    answer: str,
    chunks: Sequence[Dict[str, Any]],
    *,
    config: Optional[AnswerConfig] = None,
) -> VerificationResult:
    """
    Ask Gemini to evaluate whether the answer is grounded in the context and complete.
    Returns a structured VerificationResult.
    """
    if not chunks:
        print("========================================================")
        print("WARNING: No context chunks provided to verifier. Answer cannot be grounded.")
        print("========================================================")
        return VerificationResult(
            is_grounded=False,
            is_complete=False,
            issues=[
                VerificationIssue(
                    type="missing_context",
                    description="No context chunks were available for verification.",
                    citation_labels=[],
                )
            ],
        )

    prompt = _build_verifier_prompt(query, answer, chunks)
    # Reuse the same AnswerConfig/model; you can customize later if desired.
    cfg = config or AnswerConfig()
    raw_json_str, _ = _call_gemini(prompt, config=cfg)
    
    # print("========================================================")
    # print("Raw verifier output:")
    # print(raw_json_str)
    # print("========================================================")

    # ---- Clean Gemini output before parsing ----
    clean_json = raw_json_str.strip()

    # Remove markdown code fences like ```json or ```
    clean_json = re.sub(r"```json|```", "", clean_json).strip()

    # Extract JSON object if extra text exists
    match = re.search(r"\{.*\}", clean_json, re.DOTALL)
    if match:
        clean_json = match.group(0)
    
    try:
        data = json.loads(clean_json)
    except json.JSONDecodeError:
        # Fallback: treat as unstructured failure.
        print("========================================================")
        print("ERROR: Verifier returned non-JSON output.")
        print("Cleaned Output:", clean_json)
        print("========================================================")
        return VerificationResult(
            is_grounded=False,
            is_complete=False,
            issues=[
                VerificationIssue(
                    type="other",
                    description="Verifier returned non-JSON output.",
                    citation_labels=[],
                )
            ],
        )

    is_grounded = bool(data.get("is_grounded", False))
    is_complete = bool(data.get("is_complete", False))
    issues_raw = data.get("issues") or []

    issues: List[VerificationIssue] = []
    for item in issues_raw:
        if not isinstance(item, dict):
            continue
        issues.append(
            VerificationIssue(
                type=str(item.get("type", "other")),
                description=str(item.get("description", "")),
                citation_labels=[
                    str(lbl) for lbl in item.get("citation_labels") or []
                ],
            )
        )

    return VerificationResult(is_grounded=is_grounded, is_complete=is_complete, issues=issues)


__all__ = ["VerificationIssue", "VerificationResult", "verify_answer"]

